### ISSUE TITLE
Buttons are not fully clickable

### ISSUE THREAD

**Issue by oguzeroglu** [pinussilvestrus/clickable-prototype#6]
I noticed the buttons are not fully clickable. See the GIF below:

![klick](https://user-images.githubusercontent.com/15003836/71175367-b2811000-2267-11ea-8e0b-67721529e910.gif)

Have not seen the source codes fully yet but might be related to some hardcoded height value not working with every screen size or something, not exactly sure. _Or maybe, this is not even a bug, but a feature_

Love the project, good luck!

**Comment by pinussilvestrus** [comment]
Thanks for reporting 👍
